---
- name: awxtest
  hosts: 211.183.3.100
  become: yes
  tasks:
    - name: Create Docker service
      docker_swarm_service:
        name: test1
        state: present
        replicas: 3
        placement:
          constraints:
            - "node.role==worker"
        args: "--with-registry-auth -p 8001:80"
        image: "nginx:latest"
