---
- name: awxtest
  hosts: all
  become: yes
  tasks:
    - name: Create Docker service
      docker_service:
        name: test1
        state: present
        constraints: "node.role==worker"
        replicas: 3
        with_registry_auth: yes
        published_ports:
          - "8001:80"
        image: nginx
