---
- name: awxtest
  hosts: your_host
  become: yes
  gather_facts: false  # gather_facts를 비활성화하여 Gathering Facts 단계를 건너뜁니다.
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:
    - name: Create Docker service
      docker_swarm_service:
        name: test1
        state: present
        replicas: 3
        placement:
          constraints:
            - "node.role==worker"
        args: "--with-registry-auth -p 8001:80"
        image: "nginx:latest"
