---
- name: awxtest
  hosts: all
  become: yes
  tasks:
    - name: Docker 서비스 생성
      docker_swarm_service:
        name: test1
        state: present
        replicas: 3
        placement:
          constraints:
            - "node.role==worker"
        image: "nginx:latest"
        publish:
          - "8001:80"
      no_log: true
