---
- name: awxtest
  hosts: localhost
  become: yes
  tasks:
    - name: Create Docker service
      docker_stack:
        name: test1
        state: present
        compose:
          version: "3"
          services:
            nginx:
              image: nginx
              replicas: 3
              ports:
                - "8001:80"
              deploy:
                placement:
                  constraints:
                    - "node.role==worker"
        with_registry_auth: yes
